services:
  selenoid:
    image: "aerokube/selenoid:1.11.3"
    container_name: selenoid
    ports:
      - "4444:4444"
    networks:
      - selenoid
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/:/etc/selenoid/"
      - "/c/etc/selenoid/video:/opt/selenoid/video"
      - "/c/etc/selenoid/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/c/etc/selenoid/video
      - OVERRIDE_HTTP_PORT=4444
      - SERVICE_PORT=4444
    command: ["-conf", "/etc/selenoid/browsers.json", "-container-network", "selenoid"]

  selenoid-ui:
    image: "aerokube/selenoid-ui:1.10.11"
    container_name: selenoid-ui
    ports:
      - "8081:8080"
    environment:
      - SELENOID_URL=http://selenoid:4444
    networks:
      - selenoid
    depends_on:
      - selenoid

  test:
    build: .
    container_name: test
    networks:
      - selenoid
    volumes:
      - "./:/app"
    working_dir: /app
    depends_on:
      - selenoid
    command: ["pytest"]
    environment:
      - SELENOID_URL=http://selenoid:4444/wd/hub

networks:
  selenoid:
    name: selenoid_net
    driver: bridge